### ISSUE TITLE
Deprecate/retire the package from Laravel 9 onwards

### ISSUE THREAD

**Issue by matijakovacevic** [iaK/make-testable#2]
Was looking to use the package (good work on it so far), but news came out about similar feat baked in the framework itself.
Check it out:

https://twitter.com/LukeDowning19/status/1449391075282624515

**Comment by iaK** [comment]
Hi! 

Thanks for reaching out! 

Yes, it has just been merged into version 8 it seems. I will deprecate this package shortly.

https://github.com/laravel/framework/pull/38997#event-5465526835
